export const products = [
  {
    id: 1,
    name: "Heritage Automatic 40",
    slug: "heritage-automatic-40",
    price: 8750,
    salePrice: null,
    image: "https://picsum.photos/id/1015/800/600",
    category: "Heritage",
    collection: "Heritage",
    movement: "Automatic",
    caseSize: 40,
    isLimited: false,
    description: "A timeless dress watch featuring Geneva stripes and a hand-finished rotor.",
    specs: {
      movement: "Caliber A-01 Automatic",
      powerReserve: "42 hours",
      caseMaterial: "316L Stainless Steel",
      dial: "Sunburst Blue",
      crystal: "Sapphire with AR Coating",
      waterResistance: "100 meters",
      strap: "Hand-stitched Cognac Leather"
    }
  },
  {
    id: 2,
    name: "Chronograph Sport",
    slug: "chronograph-sport",
    price: 12400,
    salePrice: 11200,
    image: "https://picsum.photos/id/160/800/600",
    category: "Sports",
    collection: "Sports",
    movement: "Automatic Chronograph",
    caseSize: 42,
    isLimited: false,
    description: "High-performance chronograph built for precision timing.",
    specs: {
      movement: "Caliber C-03 Automatic Chronograph",
      powerReserve: "55 hours",
      caseMaterial: "Titanium Grade 5",
      dial: "Matte Black",
      crystal: "Sapphire",
      waterResistance: "200 meters",
      strap: "Integrated Titanium Bracelet"
    }
  },
  {
    id: 3,
    name: "Limited Edition Tourbillon",
    slug: "limited-tourbillon",
    price: 48500,
    salePrice: null,
    image: "https://picsum.photos/id/201/800/600",
    category: "Limited Edition",
    collection: "Limited",
    movement: "Manual Tourbillon",
    caseSize: 41,
    isLimited: true,
    description: "Only 25 pieces ever made. Features a flying tourbillon.",
    specs: {
      movement: "Caliber T-01 Manual Tourbillon",
      powerReserve: "72 hours",
      caseMaterial: "18k Rose Gold",
      dial: "Guilloché Ivory",
      crystal: "Sapphire Box Crystal",
      waterResistance: "50 meters",
      strap: "Alligator Leather"
    }
  },
  {
    id: 4,
    name: "Deep Diver 300",
    slug: "deep-diver-300",
    price: 9800,
    salePrice: null,
    image: "https://picsum.photos/id/251/800/600",
    category: "Dive",
    collection: "Sports",
    movement: "Automatic",
    caseSize: 42,
    isLimited: false,
    description: "Professional dive watch rated to 300 meters.",
    specs: {
      movement: "Caliber D-02 Automatic",
      powerReserve: "48 hours",
      caseMaterial: "Stainless Steel + Ceramic Bezel",
      dial: "Deep Black",
      crystal: "Sapphire",
      waterResistance: "300 meters",
      strap: "Rubber with Titanium Buckle"
    }
  },
  {
    id: 5,
    name: "Classic Dress 38",
    slug: "classic-dress-38",
    price: 6950,
    salePrice: null,
    image: "https://picsum.photos/id/106/800/600",
    category: "Heritage",
    collection: "Heritage",
    movement: "Automatic",
    caseSize: 38,
    isLimited: false,
    description: "Elegant and refined. Perfect for formal occasions.",
    specs: {
      movement: "Caliber A-02 Automatic",
      powerReserve: "38 hours",
      caseMaterial: "Stainless Steel",
      dial: "Champagne",
      crystal: "Sapphire",
      waterResistance: "50 meters",
      strap: "Black Calf Leather"
    }
  },
  {
    id: 6,
    name: "Pilot Chronograph",
    slug: "pilot-chronograph",
    price: 11200,
    salePrice: null,
    image: "https://picsum.photos/id/180/800/600",
    category: "Sports",
    collection: "Sports",
    movement: "Automatic Chronograph",
    caseSize: 43,
    isLimited: false,
    description: "Inspired by aviation heritage with large pushers and clear legibility.",
    specs: {
      movement: "Caliber P-01 Automatic Chronograph",
      powerReserve: "50 hours",
      caseMaterial: "Stainless Steel",
      dial: "Matte Black with Luminous Markers",
      crystal: "Sapphire",
      waterResistance: "100 meters",
      strap: "NATO Fabric or Leather"
    }
  },
  {
    id: 7,
    name: "GMT Master II",
    slug: "gmt-master-ii",
    price: 13500,
    salePrice: null,
    image: "https://picsum.photos/id/29/800/600",
    category: "Heritage",
    collection: "Heritage",
    movement: "Automatic GMT",
    caseSize: 40,
    isLimited: false,
    description: "The ultimate traveler's watch with independent 24-hour hand.",
    specs: {
      movement: "Caliber G-02 Automatic GMT",
      powerReserve: "45 hours",
      caseMaterial: "904L Stainless Steel",
      dial: "Black with Red/Blue Bezel",
      crystal: "Sapphire",
      waterResistance: "100 meters",
      strap: "Jubilee Bracelet"
    }
  },
  {
    id: 8,
    name: "Skeleton Tourbillon",
    slug: "skeleton-tourbillon",
    price: 67500,
    salePrice: null,
    image: "https://picsum.photos/id/251/800/600",
    category: "Limited Edition",
    collection: "Limited",
    movement: "Manual Tourbillon",
    caseSize: 42,
    isLimited: true,
    description: "Only 10 pieces. Fully skeletonized with visible tourbillon.",
    specs: {
      movement: "Caliber ST-01 Manual Tourbillon",
      powerReserve: "65 hours",
      caseMaterial: "Platinum 950",
      dial: "Skeletonized",
      crystal: "Sapphire",
      waterResistance: "30 meters",
      strap: "Hand-stitched Alligator"
    }
  },
  {
    id: 9,
    name: "Ultra Thin Dress",
    slug: "ultra-thin-dress",
    price: 9200,
    salePrice: null,
    image: "https://picsum.photos/id/106/800/600",
    category: "Heritage",
    collection: "Heritage",
    movement: "Automatic",
    caseSize: 39,
    isLimited: false,
    description: "Exceptionally thin at only 6.8mm. The epitome of elegance.",
    specs: {
      movement: "Caliber UT-01 Ultra Thin Automatic",
      powerReserve: "40 hours",
      caseMaterial: "18k White Gold",
      dial: "Silver Guilloché",
      crystal: "Sapphire",
      waterResistance: "30 meters",
      strap: "Black Alligator Leather"
    }
  },
  {
    id: 10,
    name: "Professional Diver Titanium",
    slug: "professional-diver-titanium",
    price: 10500,
    salePrice: null,
    image: "https://picsum.photos/id/160/800/600",
    category: "Dive",
    collection: "Sports",
    movement: "Automatic",
    caseSize: 44,
    isLimited: false,
    description: "Built for professional divers. Titanium case for comfort and strength.",
    specs: {
      movement: "Caliber PD-03 Automatic",
      powerReserve: "52 hours",
      caseMaterial: "Grade 5 Titanium",
      dial: "Deep Blue Luminous",
      crystal: "Sapphire with AR",
      waterResistance: "500 meters",
      strap: "Titanium Bracelet or Rubber"
    }
  },
  {
    id: 11,
    name: "Annual Calendar",
    slug: "annual-calendar",
    price: 24500,
    salePrice: null,
    image: "https://picsum.photos/id/201/800/600",
    category: "Heritage",
    collection: "Limited",
    movement: "Automatic Annual Calendar",
    caseSize: 41,
    isLimited: true,
    description: "Sophisticated annual calendar complication in a classic case.",
    specs: {
      movement: "Caliber AC-01 Automatic Annual Calendar",
      powerReserve: "48 hours",
      caseMaterial: "18k Rose Gold",
      dial: "Ivory with Applied Indices",
      crystal: "Sapphire",
      waterResistance: "50 meters",
      strap: "Cognac Alligator Leather"
    }
  },
  {
    id: 12,
    name: "Racing Chronograph",
    slug: "racing-chronograph",
    price: 15800,
    salePrice: null,
    image: "https://picsum.photos/id/180/800/600",
    category: "Sports",
    collection: "Sports",
    movement: "Automatic Chronograph",
    caseSize: 41,
    isLimited: false,
    description: "Inspired by classic motorsport timing. Tachymeter bezel.",
    specs: {
      movement: "Caliber RC-02 Automatic Chronograph",
      powerReserve: "46 hours",
      caseMaterial: "Stainless Steel",
      dial: "Matte Black with Red Accents",
      crystal: "Sapphire",
      waterResistance: "100 meters",
      strap: "Perforated Leather or Bracelet"
    }
  }
];
